-d C:\git programing projects\SysVerilog\essentials_gates\impl\gwsynthesis\essentials_gates.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\git programing projects\SysVerilog\essentials_gates\src\essentials_gates.cst
-cfg C:\git programing projects\SysVerilog\essentials_gates\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
